cache:
  directories:
    - $TRAVIS_BUILD_DIR/test/
    - $TRAVIS_BUILD_DIR/src/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  # - ./purge_olean.sh
  - rm mathlib.txt || true

script:
  - make
  - make leantest
